edition = "2021"
comment_width = 80
wrap_comments = true
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true
format_strings = true
max_width = 80
tab_spaces = 2
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
condense_wildcard_suffixes = true
