-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
return {
	kind = {
		Text = "",
		-- Method = 'm',
		Method = "m",
		-- Function = "",
		Function = "",
		Constructor = "",
		-- Field = "",
		Field = "",
		Variable = "",
		-- Class = '',
		Class = "𝓒",
		Interface = "",
		Module = "",
		-- Property = '',
		Property = "",
		Unit = "",
		Value = "",
		-- Enum = "",
		Enum = "ℰ",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		-- Struct = "",
		Struct = "𝓢",
		-- Event = "",
		Event = "🗲",
		-- Operator = "",
		Operator = "+",
		-- TypeParameter = "",
		TypeParameter = "𝙏",
	},
	type = {
		Array = "",
		Number = "#",
		String = "",
		Boolean = "⊨",
		Object = "",
	},
	documents = {
		-- File = "",
		File = "",
		Files = "",
		Folder = "",
		OpenFolder = "",
	},
	git = {
		Add = "",
		Mod = "",
		Remove = "",
		Ignore = "",
		Rename = "",
		Diff = "",
		Repo = "",
	},
	ui = {
		Lock = "",
		Circle = "",
		BigCircle = "",
		BigUnfilledCircle = "",
		Close = "",
		NewFile = "",
		Search = "",
		Lightbulb = "",
		Project = "",
		Dashboard = "",
		History = "",
		Comment = "",
		Bug = "",
		Code = "",
		Telescope = "",
		Gear = "",
		Package = "",
		List = "",
		SignIn = "",
		Check = "",
		Fire = "",
		Note = "",
		BookMark = "",
		Pencil = "",
		-- ChevronRight = "",
		ChevronRight = ">",
		Table = "",
		Calendar = "",
	},
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Question = "",
		Hint = "",
	},
	misc = {
		Robot = "ﮧ",
		Squirrel = "",
		Tag = "",
		Watch = "",
	},

  bufferline = {
    BuffClose = "",
    Close = "",
    Indicator = "▎",
    Modified = "●",
  },
  go = {
    BreakPoint = "🧘",
    CurrentPos = "🏃",
    CommentPlaceHolder = "ﳑ",
    Prefix = "",
  },
  telescope = {
    PromptPrefix = " ",
    SelectionCaret = " ",
  },
}
