# mac = ~/Library/Application\ Support/lazygit/config.yml
---
os:
  editCommand: 'floaterm'
gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
